### ISSUE TITLE
Use std.fileread() instead of directly embedding 500 error page?

### ISSUE THREAD

**Issue by quicksketch** [Lullabot/varnish#5]
It's a fairly common practice to use [`std.fileread()`](https://www.varnish-cache.org/docs/3.0/reference/vmod_std.html#fileread) to create synthetic HTML pages in Varnish. Perhaps we should include an example of how to do this?

```
sub vcl_error {
  set obj.http.Content-Type = "text/html; charset=utf-8";
  synthetic std.fileread("/etc/varnishd/500.html");
  return (deliver);
}
```

The current example we have is perhaps more universal in that it's easier to copy/paste, and it includes the error message as part of the response, both of which are useful features. But there may be a lot of sites out there that would like a more elaborate error page, in which embedding directly in the VCL may not be practical.

**Comment by q0rban** [comment]
Cool! I didn't know about this.

**Comment by bchavet** [comment]
Huh, I didn't know about this either. I'd say this is definitely worth an example.

**Comment by quicksketch** [comment]
Yeah seems like a good thing to do. Although I'm having trouble getting it to work on my localhost 3.x setup. Here's a blog post: http://blog.tenya.me/blog/2012/06/25/varnish-3-dot-x-custom-error-pages/

**Comment by quicksketch** [comment]
> Although I'm having trouble getting it to work on my localhost 3.x setup.

Turned out this was a directory permissions issue on my local. The example I posted above seems to work on a server where permissions are more typical.

**Comment by deviantintegral** [comment]
:+1:

**Comment by mgzrobles** [comment]
hi! you have an answers for use std.fileread vs include "conf.d/error.vcl";  ??
